[versions]
junit5 = "5.8.2"
crowdin = "1.0.0"
ustats = "1.0.0"
universalcraft = "262"
bstats = "3.0.2"

[libraries]
lombok       = { module = "org.projectlombok:lombok", version = "1.18.24" }
annotations  = { module = "org.jetbrains:annotations", version = "23.0.0" }
guava        = { module = "com.google.guava:guava", version = "31.1-jre" }
gson         = { module = "com.google.code.gson:gson", version = "2.9.0" }

slf4j        = { module = "org.slf4j:slf4j-api", version = "1.7.30" }
junit-api    = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
opus         = { module = "su.plo.opus:opus", version = "2.0.0" }
rnnoise      = { module = "su.plo.rnnoise:rnnoise", version = "2.0.0" }
netty        = { module = "io.netty:netty-all", version = "4.1.77.Final"}
config       = { module = "su.plo.config:config", version = "1.0.1" }
luckperms    = { module = "net.luckperms:api", version = "5.4" }

guice        = { module = "com.google.inject:guice", version = "5.0.1" }
javax-inject = { module = "javax.inject:javax.inject", version = "1" }
aopalliance  = { module = "aopalliance:aopalliance", version = "1.0" }

kotlinx-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.3.2" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.1" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version = "1.6.1" }

crowdin-lib = { module = "su.plo.crowdin:lib", version.ref = "crowdin" }

[plugins]
architectury-plugin = { id = "architectury-plugin", version = "3.4-SNAPSHOT" }
architectury-loom   = { id = "dev.architectury.loom", version = "0.12.0-SNAPSHOT" }
shadow              = { id = "com.github.johnrengelman.shadow", version = "7.1.0" }
idea-ext            = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.1.7"}
crowdin-plugin      = { id = "su.plo.crowdin.plugin", version.ref = "crowdin" }
