[versions]
kotlin = "1.9.23"
dokka = "1.8.20"
kotlinx-json = "1.5.1"
kotlinx-coroutines = "1.7.3"

junit5 = "5.8.2"

lombok = "1.18.32"
annotations = "23.0.0"
guava = "31.1-jre"
gson = "2.10.1"
netty = "4.1.77.Final"
crowdin = "1.0.2-SNAPSHOT"
config = "1.0.2"
slib = "1.0.0-SNAPSHOT"
bstats = "3.0.2"
luckperms = "5.4"
papi = "2.11.2"
supervanish = "6.2.18-3"

bungeecord = "1.19-R0.1-SNAPSHOT"
velocity = "3.1.1"
paper = "1.16.5-R0.1-SNAPSHOT"

minestom = "7320437640"
minestom-extensions = "1.2.0"

opus-jni = "1.0.3"
opus-concentus = "acaadf2075"
rnnoise-jni = "1.0.2"

shadow = "8.1.1"
idea-ext = "1.1.7"

asm = "9.6"

[libraries]
kotlinx-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-json" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }

junit-api    = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }

lombok       = { module = "org.projectlombok:lombok", version.ref = "lombok" }
annotations  = { module = "org.jetbrains:annotations", version.ref = "annotations" }
guava        = { module = "com.google.guava:guava", version.ref = "guava" }
gson         = { module = "com.google.code.gson:gson", version.ref = "gson" }
javax-inject = { module = "javax.inject:javax.inject", version = "1" }
aopalliance  = { module = "aopalliance:aopalliance", version = "1.0" }
netty        = { module = "io.netty:netty-all", version.ref = "netty"}
crowdin      = { module = "su.plo.crowdin:lib", version.ref = "crowdin" }
config       = { module = "su.plo.config:config", version.ref = "config" }
luckperms    = { module = "net.luckperms:api", version.ref = "luckperms" }
papi         = { module = "me.clip:placeholderapi", version.ref = "papi" }
supervanish = { module = "com.github.LeonMangler:SuperVanish", version.ref = "supervanish" }

bungeecord   = { module = "net.md-5:bungeecord-api", version.ref = "bungeecord"}
velocity     = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
paper        = { module = "com.destroystokyo.paper:paper-api", version.ref = "paper" }

minestom = { module = "net.minestom:minestom-snapshots", version.ref = "minestom" }
minestom-extension = { module = "dev.hollowcube:minestom-ce-extensions", version.ref = "minestom-extensions" }

opus-jni     = { module = "com.plasmoverse:opus-jni-rust", version.ref = "opus-jni" }
opus-concentus = { module = "com.github.lostromb.concentus:Concentus", version.ref = "opus-concentus" }
rnnoise-jni  = { module = "com.plasmoverse:rnnoise-jni-rust", version.ref = "rnnoise-jni" }

shadow = { module = "com.github.johnrengelman:shadow", version.ref = "shadow" }
asm = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }

[plugins]
idea-ext            = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "idea-ext"}
crowdin             = { id = "su.plo.crowdin.plugin", version.ref = "crowdin" }
dokka               = { id = "org.jetbrains.dokka", version.ref = "dokka" }
